# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modify_data.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import QDialog
import sqlite3
class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        QDialog.__init__(self)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("MainWindow_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setObjectName("Dialog")
        Dialog.resize(513, 518)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 80, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(140, 181, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(220, 190, 131, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(220, 230, 131, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(220, 270, 131, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(140, 220, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(140, 260, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 310, 211, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(222, 349, 131, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(140, 350, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 400, 211, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton.clicked.connect(self.get_last_data)
        self.pushButton_2.clicked.connect(self.modify)
        self.retranslateUi(Dialog)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Modify companies dataBase"))
        self.label_2.setText(_translate("Dialog", "name:"))
        self.comboBox.setItemText(0, _translate("Dialog", "资产负债率"))
        self.comboBox.setItemText(1, _translate("Dialog", "长期资金占不动产/厂房及设备比率"))
        self.comboBox.setItemText(2, _translate("Dialog", "流动比率"))
        self.comboBox.setItemText(3, _translate("Dialog", "速动比率"))
        self.comboBox.setItemText(4, _translate("Dialog", "应收款项周转率"))
        self.comboBox.setItemText(5, _translate("Dialog", "应收账款周转天数"))
        self.comboBox.setItemText(6, _translate("Dialog", "存货周转率"))
        self.comboBox.setItemText(7, _translate("Dialog", "存货周转天数"))
        self.comboBox.setItemText(8, _translate("Dialog", "固定资产周转率"))
        self.comboBox.setItemText(9, _translate("Dialog", "资产收益率"))
        self.comboBox.setItemText(10, _translate("Dialog", "净资产收益率"))
        self.comboBox.setItemText(11, _translate("Dialog", "税前纯益占实收资本比率"))
        self.comboBox.setItemText(12, _translate("Dialog", "生意完整周期"))
        self.comboBox.setItemText(13, _translate("Dialog", "总资产周转率"))
        self.comboBox.setItemText(14, _translate("Dialog", "EPS_每股收益"))
        self.comboBox.setItemText(15, _translate("Dialog", "营收增长率"))
        self.comboBox.setItemText(16, _translate("Dialog", "净利润增长率"))
        self.comboBox.setItemText(17, _translate("Dialog", "净资产增长率"))
        self.comboBox.setItemText(18, _translate("Dialog", "现金流量比率"))
        self.comboBox.setItemText(19, _translate("Dialog", "现金流量允当比率"))
        self.comboBox.setItemText(20, _translate("Dialog", "现金再投资比率"))
        self.comboBox.setItemText(21, _translate("Dialog", "毛利率"))
        self.comboBox.setItemText(22, _translate("Dialog", "营业利润率"))
        self.comboBox.setItemText(23, _translate("Dialog", "净利润率"))
        self.comboBox.setItemText(24, _translate("Dialog", "营业费用率"))
        self.comboBox.setItemText(25, _translate("Dialog", "经营安全边际率 "))
        self.comboBox.setItemText(26, _translate("Dialog", "现金与约当现金比率"))
        self.comboBox.setItemText(27, _translate("Dialog", "应收款项(占总资产%)"))
        self.comboBox.setItemText(28, _translate("Dialog", "存货(占总资产%)"))
        self.comboBox.setItemText(29, _translate("Dialog", "流动资产(占总资产%)"))
        self.comboBox.setItemText(30, _translate("Dialog", "非流动资产"))
        self.comboBox.setItemText(31, _translate("Dialog", "总资产(占总资产%)"))
        self.comboBox.setItemText(32, _translate("Dialog", "应付款项(占总资产%)"))
        self.comboBox.setItemText(33, _translate("Dialog", "流动负债(占总资产%)"))
        self.comboBox.setItemText(34, _translate("Dialog", "非流动负债(占总资产%)"))
        self.comboBox.setItemText(35, _translate("Dialog", "股东权益(占总资产%)"))
        self.comboBox.setItemText(36, _translate("Dialog", "负债和所有者权益(占总资产%)"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Yeas_2017"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Yeas_2016"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Yeas_2015"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "Yeas_2014"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "Yeas_2013"))
        self.label_3.setText(_translate("Dialog", "rate:"))
        self.label_4.setText(_translate("Dialog", "Years:"))
        self.pushButton.setText(_translate("Dialog", "Get last data"))
        self.label_5.setText(_translate("Dialog", "new data:"))
        self.pushButton_2.setText(_translate("Dialog", "confirm to updata"))
    def get_last_data(self):
        str_1=self.lineEdit.text()#获取需要修改的公司名
        str_2=self.comboBox.currentText()#获取需要修改的公司的rate
        str_3=self.comboBox_2.currentText()#获取需要修改的公司的rate的年份
        str = self.lineEdit.text()  # 获取输入框数据
        conn = sqlite3.connect(r'db\dataBase.db')
        conn.isolation_level = None
        conn.commit()
        cur = conn.cursor()
#         print(str_1,str_2,str_3)
        try:#判断打开文件是否出错
#                 QtWidgets.QMessageBox.information(self,"提示","注册成功",QtWidgets.QMessageBox.Yes,QtWidgets.QMessageBox.No)
#             cur.execute("select %s \t from %s \t where id=%s \tand " %(str_3,str_1,str_2)),here id=yeas_2017 
            cur.execute("select %s from %s where id='%s'"%(str_3,str_1,str_2))
            res = cur.fetchall()
            str_data=''.join(res[0])
            QtWidgets.QMessageBox.information(self,"info","old data is\t"+str_data)
            cur.close()
            conn.close()
#                 QtWidgets.QMessageBox.information(self,"提示","注册成功",QtWidgets.QMessageBox.Yes,QtWidgets.QMessageBox.No)
        except Exception as err:
#             print("laji")
            print(err)
    def modify(self):
        str_1=self.lineEdit.text()#获取需要修改的公司名
        str_2=self.comboBox.currentText()#获取需要修改的公司的rate
        str_3=self.comboBox_2.currentText()#获取需要修改的公司的rate的年份
        str_4 = self.lineEdit_2.text()  # 获取输入框数据
        str=self.lineEdit_2.text()#UPDATE 表名称 SET 列名称 = 新值 WHERE 列名称 = 某值
        conn = sqlite3.connect(r'db\dataBase.db')
        conn.isolation_level = None
        
        cur = conn.cursor()
        try:#判断打开文件是否出错
#                 QtWidgets.QMessageBox.information(self,"提示","注册成功",QtWidgets.QMessageBox.Yes,QtWidgets.QMessageBox.No)
#             cur.execute("select %s \t from %s \t where id=%s \tand " %(str_3,str_1,str_2)),here id=yeas_2017 
            cur.execute("update  %s set '%s'=%s where id='%s'"%(str_1,str_3,str_4,str_2))
            res = cur.fetchall()
#             str_data=''.join(res[0])
            QtWidgets.QMessageBox.information(self,"info","更新成功")
            conn.commit()
            cur.close()
            conn.close()
#                 QtWidgets.QMessageBox.information(self,"提示","注册成功",QtWidgets.QMessageBox.Yes,QtWidgets.QMessageBox.No)
        except Exception as err:
#             print("laji")
            print(err)
        
class query_interface(QDialog):
#     print("hah")
    def __init__(self):
      super(query_interface, self).__init__()
      self.ui=Ui_Dialog()
      self.ui.setupUi(self)
if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    myapp=query_interface()
    #myapp.setupUi()
    myapp.exec_()
    sys.exit(app.exec_())
