# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_company.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import QDialog
import sqlite3
class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        QDialog.__init__(self)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("MainWindow_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setObjectName("Dialog")
        Dialog.resize(1207, 708)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 100, 111, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(30, 120, 111, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 120, 391, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spinBox_6 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_6.addWidget(self.spinBox_6)
        self.spinBox_7 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_7.setObjectName("spinBox_7")
        self.horizontalLayout_6.addWidget(self.spinBox_7)
        self.spinBox_8 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_6.addWidget(self.spinBox_8)
        self.spinBox_9 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_6.addWidget(self.spinBox_9)
        self.spinBox_10 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_6.addWidget(self.spinBox_10)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(140, 140, 391, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.spinBox_11 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_11.setObjectName("spinBox_11")
        self.horizontalLayout_10.addWidget(self.spinBox_11)
        self.spinBox_12 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_12.setObjectName("spinBox_12")
        self.horizontalLayout_10.addWidget(self.spinBox_12)
        self.spinBox_13 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_13.setObjectName("spinBox_13")
        self.horizontalLayout_10.addWidget(self.spinBox_13)
        self.spinBox_14 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_14.setObjectName("spinBox_14")
        self.horizontalLayout_10.addWidget(self.spinBox_14)
        self.spinBox_15 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_15.setObjectName("spinBox_15")
        self.horizontalLayout_10.addWidget(self.spinBox_15)
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(30, 140, 111, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.layoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(140, 160, 391, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.spinBox_16 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_16.setObjectName("spinBox_16")
        self.horizontalLayout_11.addWidget(self.spinBox_16)
        self.spinBox_17 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_17.setObjectName("spinBox_17")
        self.horizontalLayout_11.addWidget(self.spinBox_17)
        self.spinBox_18 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_18.setObjectName("spinBox_18")
        self.horizontalLayout_11.addWidget(self.spinBox_18)
        self.spinBox_19 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_19.setObjectName("spinBox_19")
        self.horizontalLayout_11.addWidget(self.spinBox_19)
        self.spinBox_20 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_20.setObjectName("spinBox_20")
        self.horizontalLayout_11.addWidget(self.spinBox_20)
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(30, 160, 111, 20))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.layoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_4.setGeometry(QtCore.QRect(140, 180, 391, 22))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.spinBox_21 = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.spinBox_21.setObjectName("spinBox_21")
        self.horizontalLayout_12.addWidget(self.spinBox_21)
        self.spinBox_22 = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.spinBox_22.setObjectName("spinBox_22")
        self.horizontalLayout_12.addWidget(self.spinBox_22)
        self.spinBox_23 = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.spinBox_23.setObjectName("spinBox_23")
        self.horizontalLayout_12.addWidget(self.spinBox_23)
        self.spinBox_24 = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.spinBox_24.setObjectName("spinBox_24")
        self.horizontalLayout_12.addWidget(self.spinBox_24)
        self.spinBox_25 = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.spinBox_25.setObjectName("spinBox_25")
        self.horizontalLayout_12.addWidget(self.spinBox_25)
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(30, 180, 111, 20))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.layoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_5.setGeometry(QtCore.QRect(140, 200, 391, 22))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.spinBox_26 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.spinBox_26.setObjectName("spinBox_26")
        self.horizontalLayout_13.addWidget(self.spinBox_26)
        self.spinBox_27 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.spinBox_27.setObjectName("spinBox_27")
        self.horizontalLayout_13.addWidget(self.spinBox_27)
        self.spinBox_28 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.spinBox_28.setObjectName("spinBox_28")
        self.horizontalLayout_13.addWidget(self.spinBox_28)
        self.spinBox_29 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.spinBox_29.setObjectName("spinBox_29")
        self.horizontalLayout_13.addWidget(self.spinBox_29)
        self.spinBox_30 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.spinBox_30.setObjectName("spinBox_30")
        self.horizontalLayout_13.addWidget(self.spinBox_30)
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(30, 200, 111, 20))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.layoutWidget_6 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_6.setGeometry(QtCore.QRect(140, 220, 391, 22))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.spinBox_31 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.spinBox_31.setObjectName("spinBox_31")
        self.horizontalLayout_14.addWidget(self.spinBox_31)
        self.spinBox_32 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.spinBox_32.setObjectName("spinBox_32")
        self.horizontalLayout_14.addWidget(self.spinBox_32)
        self.spinBox_33 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.spinBox_33.setObjectName("spinBox_33")
        self.horizontalLayout_14.addWidget(self.spinBox_33)
        self.spinBox_34 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.spinBox_34.setObjectName("spinBox_34")
        self.horizontalLayout_14.addWidget(self.spinBox_34)
        self.spinBox_35 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.spinBox_35.setObjectName("spinBox_35")
        self.horizontalLayout_14.addWidget(self.spinBox_35)
        self.comboBox_7 = QtWidgets.QComboBox(Dialog)
        self.comboBox_7.setGeometry(QtCore.QRect(30, 220, 111, 20))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.layoutWidget_7 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_7.setGeometry(QtCore.QRect(140, 240, 391, 22))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.spinBox_36 = QtWidgets.QSpinBox(self.layoutWidget_7)
        self.spinBox_36.setObjectName("spinBox_36")
        self.horizontalLayout_15.addWidget(self.spinBox_36)
        self.spinBox_37 = QtWidgets.QSpinBox(self.layoutWidget_7)
        self.spinBox_37.setObjectName("spinBox_37")
        self.horizontalLayout_15.addWidget(self.spinBox_37)
        self.spinBox_38 = QtWidgets.QSpinBox(self.layoutWidget_7)
        self.spinBox_38.setObjectName("spinBox_38")
        self.horizontalLayout_15.addWidget(self.spinBox_38)
        self.spinBox_39 = QtWidgets.QSpinBox(self.layoutWidget_7)
        self.spinBox_39.setObjectName("spinBox_39")
        self.horizontalLayout_15.addWidget(self.spinBox_39)
        self.spinBox_40 = QtWidgets.QSpinBox(self.layoutWidget_7)
        self.spinBox_40.setObjectName("spinBox_40")
        self.horizontalLayout_15.addWidget(self.spinBox_40)
        self.comboBox_8 = QtWidgets.QComboBox(Dialog)
        self.comboBox_8.setGeometry(QtCore.QRect(30, 240, 111, 20))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.layoutWidget_8 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_8.setGeometry(QtCore.QRect(140, 260, 391, 22))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.spinBox_41 = QtWidgets.QSpinBox(self.layoutWidget_8)
        self.spinBox_41.setObjectName("spinBox_41")
        self.horizontalLayout_16.addWidget(self.spinBox_41)
        self.spinBox_42 = QtWidgets.QSpinBox(self.layoutWidget_8)
        self.spinBox_42.setObjectName("spinBox_42")
        self.horizontalLayout_16.addWidget(self.spinBox_42)
        self.spinBox_43 = QtWidgets.QSpinBox(self.layoutWidget_8)
        self.spinBox_43.setObjectName("spinBox_43")
        self.horizontalLayout_16.addWidget(self.spinBox_43)
        self.spinBox_44 = QtWidgets.QSpinBox(self.layoutWidget_8)
        self.spinBox_44.setObjectName("spinBox_44")
        self.horizontalLayout_16.addWidget(self.spinBox_44)
        self.spinBox_45 = QtWidgets.QSpinBox(self.layoutWidget_8)
        self.spinBox_45.setObjectName("spinBox_45")
        self.horizontalLayout_16.addWidget(self.spinBox_45)
        self.layoutWidget_9 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_9.setGeometry(QtCore.QRect(140, 280, 391, 22))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.spinBox_46 = QtWidgets.QSpinBox(self.layoutWidget_9)
        self.spinBox_46.setObjectName("spinBox_46")
        self.horizontalLayout_17.addWidget(self.spinBox_46)
        self.spinBox_47 = QtWidgets.QSpinBox(self.layoutWidget_9)
        self.spinBox_47.setObjectName("spinBox_47")
        self.horizontalLayout_17.addWidget(self.spinBox_47)
        self.spinBox_48 = QtWidgets.QSpinBox(self.layoutWidget_9)
        self.spinBox_48.setObjectName("spinBox_48")
        self.horizontalLayout_17.addWidget(self.spinBox_48)
        self.spinBox_49 = QtWidgets.QSpinBox(self.layoutWidget_9)
        self.spinBox_49.setObjectName("spinBox_49")
        self.horizontalLayout_17.addWidget(self.spinBox_49)
        self.spinBox_50 = QtWidgets.QSpinBox(self.layoutWidget_9)
        self.spinBox_50.setObjectName("spinBox_50")
        self.horizontalLayout_17.addWidget(self.spinBox_50)
        self.layoutWidget_10 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_10.setGeometry(QtCore.QRect(140, 300, 391, 22))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.spinBox_51 = QtWidgets.QSpinBox(self.layoutWidget_10)
        self.spinBox_51.setObjectName("spinBox_51")
        self.horizontalLayout_18.addWidget(self.spinBox_51)
        self.spinBox_52 = QtWidgets.QSpinBox(self.layoutWidget_10)
        self.spinBox_52.setObjectName("spinBox_52")
        self.horizontalLayout_18.addWidget(self.spinBox_52)
        self.spinBox_53 = QtWidgets.QSpinBox(self.layoutWidget_10)
        self.spinBox_53.setObjectName("spinBox_53")
        self.horizontalLayout_18.addWidget(self.spinBox_53)
        self.spinBox_54 = QtWidgets.QSpinBox(self.layoutWidget_10)
        self.spinBox_54.setObjectName("spinBox_54")
        self.horizontalLayout_18.addWidget(self.spinBox_54)
        self.spinBox_55 = QtWidgets.QSpinBox(self.layoutWidget_10)
        self.spinBox_55.setObjectName("spinBox_55")
        self.horizontalLayout_18.addWidget(self.spinBox_55)
        self.layoutWidget_11 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_11.setGeometry(QtCore.QRect(140, 320, 391, 22))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.spinBox_56 = QtWidgets.QSpinBox(self.layoutWidget_11)
        self.spinBox_56.setObjectName("spinBox_56")
        self.horizontalLayout_19.addWidget(self.spinBox_56)
        self.spinBox_57 = QtWidgets.QSpinBox(self.layoutWidget_11)
        self.spinBox_57.setObjectName("spinBox_57")
        self.horizontalLayout_19.addWidget(self.spinBox_57)
        self.spinBox_58 = QtWidgets.QSpinBox(self.layoutWidget_11)
        self.spinBox_58.setObjectName("spinBox_58")
        self.horizontalLayout_19.addWidget(self.spinBox_58)
        self.spinBox_59 = QtWidgets.QSpinBox(self.layoutWidget_11)
        self.spinBox_59.setObjectName("spinBox_59")
        self.horizontalLayout_19.addWidget(self.spinBox_59)
        self.spinBox_60 = QtWidgets.QSpinBox(self.layoutWidget_11)
        self.spinBox_60.setObjectName("spinBox_60")
        self.horizontalLayout_19.addWidget(self.spinBox_60)
        self.layoutWidget_12 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_12.setGeometry(QtCore.QRect(140, 340, 391, 22))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.layoutWidget_12)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.spinBox_61 = QtWidgets.QSpinBox(self.layoutWidget_12)
        self.spinBox_61.setObjectName("spinBox_61")
        self.horizontalLayout_20.addWidget(self.spinBox_61)
        self.spinBox_62 = QtWidgets.QSpinBox(self.layoutWidget_12)
        self.spinBox_62.setObjectName("spinBox_62")
        self.horizontalLayout_20.addWidget(self.spinBox_62)
        self.spinBox_63 = QtWidgets.QSpinBox(self.layoutWidget_12)
        self.spinBox_63.setObjectName("spinBox_63")
        self.horizontalLayout_20.addWidget(self.spinBox_63)
        self.spinBox_64 = QtWidgets.QSpinBox(self.layoutWidget_12)
        self.spinBox_64.setObjectName("spinBox_64")
        self.horizontalLayout_20.addWidget(self.spinBox_64)
        self.spinBox_65 = QtWidgets.QSpinBox(self.layoutWidget_12)
        self.spinBox_65.setObjectName("spinBox_65")
        self.horizontalLayout_20.addWidget(self.spinBox_65)
        self.layoutWidget_13 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_13.setGeometry(QtCore.QRect(140, 360, 391, 22))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget_13)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.spinBox_66 = QtWidgets.QSpinBox(self.layoutWidget_13)
        self.spinBox_66.setObjectName("spinBox_66")
        self.horizontalLayout_21.addWidget(self.spinBox_66)
        self.spinBox_67 = QtWidgets.QSpinBox(self.layoutWidget_13)
        self.spinBox_67.setObjectName("spinBox_67")
        self.horizontalLayout_21.addWidget(self.spinBox_67)
        self.spinBox_68 = QtWidgets.QSpinBox(self.layoutWidget_13)
        self.spinBox_68.setObjectName("spinBox_68")
        self.horizontalLayout_21.addWidget(self.spinBox_68)
        self.spinBox_69 = QtWidgets.QSpinBox(self.layoutWidget_13)
        self.spinBox_69.setObjectName("spinBox_69")
        self.horizontalLayout_21.addWidget(self.spinBox_69)
        self.spinBox_70 = QtWidgets.QSpinBox(self.layoutWidget_13)
        self.spinBox_70.setObjectName("spinBox_70")
        self.horizontalLayout_21.addWidget(self.spinBox_70)
        self.layoutWidget_14 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_14.setGeometry(QtCore.QRect(140, 380, 391, 22))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.spinBox_71 = QtWidgets.QSpinBox(self.layoutWidget_14)
        self.spinBox_71.setObjectName("spinBox_71")
        self.horizontalLayout_22.addWidget(self.spinBox_71)
        self.spinBox_72 = QtWidgets.QSpinBox(self.layoutWidget_14)
        self.spinBox_72.setObjectName("spinBox_72")
        self.horizontalLayout_22.addWidget(self.spinBox_72)
        self.spinBox_73 = QtWidgets.QSpinBox(self.layoutWidget_14)
        self.spinBox_73.setObjectName("spinBox_73")
        self.horizontalLayout_22.addWidget(self.spinBox_73)
        self.spinBox_74 = QtWidgets.QSpinBox(self.layoutWidget_14)
        self.spinBox_74.setObjectName("spinBox_74")
        self.horizontalLayout_22.addWidget(self.spinBox_74)
        self.spinBox_75 = QtWidgets.QSpinBox(self.layoutWidget_14)
        self.spinBox_75.setObjectName("spinBox_75")
        self.horizontalLayout_22.addWidget(self.spinBox_75)
        self.layoutWidget_15 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_15.setGeometry(QtCore.QRect(140, 400, 391, 22))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget_15)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.spinBox_76 = QtWidgets.QSpinBox(self.layoutWidget_15)
        self.spinBox_76.setObjectName("spinBox_76")
        self.horizontalLayout_23.addWidget(self.spinBox_76)
        self.spinBox_77 = QtWidgets.QSpinBox(self.layoutWidget_15)
        self.spinBox_77.setObjectName("spinBox_77")
        self.horizontalLayout_23.addWidget(self.spinBox_77)
        self.spinBox_78 = QtWidgets.QSpinBox(self.layoutWidget_15)
        self.spinBox_78.setObjectName("spinBox_78")
        self.horizontalLayout_23.addWidget(self.spinBox_78)
        self.spinBox_79 = QtWidgets.QSpinBox(self.layoutWidget_15)
        self.spinBox_79.setObjectName("spinBox_79")
        self.horizontalLayout_23.addWidget(self.spinBox_79)
        self.spinBox_80 = QtWidgets.QSpinBox(self.layoutWidget_15)
        self.spinBox_80.setObjectName("spinBox_80")
        self.horizontalLayout_23.addWidget(self.spinBox_80)
        self.layoutWidget_16 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_16.setGeometry(QtCore.QRect(140, 420, 391, 22))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.layoutWidget_16)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.spinBox_81 = QtWidgets.QSpinBox(self.layoutWidget_16)
        self.spinBox_81.setObjectName("spinBox_81")
        self.horizontalLayout_24.addWidget(self.spinBox_81)
        self.spinBox_82 = QtWidgets.QSpinBox(self.layoutWidget_16)
        self.spinBox_82.setObjectName("spinBox_82")
        self.horizontalLayout_24.addWidget(self.spinBox_82)
        self.spinBox_83 = QtWidgets.QSpinBox(self.layoutWidget_16)
        self.spinBox_83.setObjectName("spinBox_83")
        self.horizontalLayout_24.addWidget(self.spinBox_83)
        self.spinBox_84 = QtWidgets.QSpinBox(self.layoutWidget_16)
        self.spinBox_84.setObjectName("spinBox_84")
        self.horizontalLayout_24.addWidget(self.spinBox_84)
        self.spinBox_85 = QtWidgets.QSpinBox(self.layoutWidget_16)
        self.spinBox_85.setObjectName("spinBox_85")
        self.horizontalLayout_24.addWidget(self.spinBox_85)
        self.layoutWidget_17 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_17.setGeometry(QtCore.QRect(140, 440, 391, 22))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.layoutWidget_17)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.spinBox_86 = QtWidgets.QSpinBox(self.layoutWidget_17)
        self.spinBox_86.setObjectName("spinBox_86")
        self.horizontalLayout_25.addWidget(self.spinBox_86)
        self.spinBox_87 = QtWidgets.QSpinBox(self.layoutWidget_17)
        self.spinBox_87.setObjectName("spinBox_87")
        self.horizontalLayout_25.addWidget(self.spinBox_87)
        self.spinBox_88 = QtWidgets.QSpinBox(self.layoutWidget_17)
        self.spinBox_88.setObjectName("spinBox_88")
        self.horizontalLayout_25.addWidget(self.spinBox_88)
        self.spinBox_89 = QtWidgets.QSpinBox(self.layoutWidget_17)
        self.spinBox_89.setObjectName("spinBox_89")
        self.horizontalLayout_25.addWidget(self.spinBox_89)
        self.spinBox_90 = QtWidgets.QSpinBox(self.layoutWidget_17)
        self.spinBox_90.setObjectName("spinBox_90")
        self.horizontalLayout_25.addWidget(self.spinBox_90)
        self.layoutWidget_18 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_18.setGeometry(QtCore.QRect(140, 460, 391, 22))
        self.layoutWidget_18.setObjectName("layoutWidget_18")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.layoutWidget_18)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.spinBox_91 = QtWidgets.QSpinBox(self.layoutWidget_18)
        self.spinBox_91.setObjectName("spinBox_91")
        self.horizontalLayout_26.addWidget(self.spinBox_91)
        self.spinBox_92 = QtWidgets.QSpinBox(self.layoutWidget_18)
        self.spinBox_92.setObjectName("spinBox_92")
        self.horizontalLayout_26.addWidget(self.spinBox_92)
        self.spinBox_93 = QtWidgets.QSpinBox(self.layoutWidget_18)
        self.spinBox_93.setObjectName("spinBox_93")
        self.horizontalLayout_26.addWidget(self.spinBox_93)
        self.spinBox_94 = QtWidgets.QSpinBox(self.layoutWidget_18)
        self.spinBox_94.setObjectName("spinBox_94")
        self.horizontalLayout_26.addWidget(self.spinBox_94)
        self.spinBox_95 = QtWidgets.QSpinBox(self.layoutWidget_18)
        self.spinBox_95.setObjectName("spinBox_95")
        self.horizontalLayout_26.addWidget(self.spinBox_95)
        self.layoutWidget_19 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_19.setGeometry(QtCore.QRect(140, 480, 391, 22))
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.layoutWidget_19)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.spinBox_96 = QtWidgets.QSpinBox(self.layoutWidget_19)
        self.spinBox_96.setObjectName("spinBox_96")
        self.horizontalLayout_27.addWidget(self.spinBox_96)
        self.spinBox_97 = QtWidgets.QSpinBox(self.layoutWidget_19)
        self.spinBox_97.setObjectName("spinBox_97")
        self.horizontalLayout_27.addWidget(self.spinBox_97)
        self.spinBox_98 = QtWidgets.QSpinBox(self.layoutWidget_19)
        self.spinBox_98.setObjectName("spinBox_98")
        self.horizontalLayout_27.addWidget(self.spinBox_98)
        self.spinBox_99 = QtWidgets.QSpinBox(self.layoutWidget_19)
        self.spinBox_99.setObjectName("spinBox_99")
        self.horizontalLayout_27.addWidget(self.spinBox_99)
        self.spinBox_100 = QtWidgets.QSpinBox(self.layoutWidget_19)
        self.spinBox_100.setObjectName("spinBox_100")
        self.horizontalLayout_27.addWidget(self.spinBox_100)
        self.layoutWidget_20 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_20.setGeometry(QtCore.QRect(140, 500, 391, 22))
        self.layoutWidget_20.setObjectName("layoutWidget_20")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.layoutWidget_20)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.spinBox_101 = QtWidgets.QSpinBox(self.layoutWidget_20)
        self.spinBox_101.setObjectName("spinBox_101")
        self.horizontalLayout_28.addWidget(self.spinBox_101)
        self.spinBox_102 = QtWidgets.QSpinBox(self.layoutWidget_20)
        self.spinBox_102.setObjectName("spinBox_102")
        self.horizontalLayout_28.addWidget(self.spinBox_102)
        self.spinBox_103 = QtWidgets.QSpinBox(self.layoutWidget_20)
        self.spinBox_103.setObjectName("spinBox_103")
        self.horizontalLayout_28.addWidget(self.spinBox_103)
        self.spinBox_104 = QtWidgets.QSpinBox(self.layoutWidget_20)
        self.spinBox_104.setObjectName("spinBox_104")
        self.horizontalLayout_28.addWidget(self.spinBox_104)
        self.spinBox_105 = QtWidgets.QSpinBox(self.layoutWidget_20)
        self.spinBox_105.setObjectName("spinBox_105")
        self.horizontalLayout_28.addWidget(self.spinBox_105)
        self.layoutWidget_21 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_21.setGeometry(QtCore.QRect(140, 520, 391, 22))
        self.layoutWidget_21.setObjectName("layoutWidget_21")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.layoutWidget_21)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.spinBox_106 = QtWidgets.QSpinBox(self.layoutWidget_21)
        self.spinBox_106.setObjectName("spinBox_106")
        self.horizontalLayout_29.addWidget(self.spinBox_106)
        self.spinBox_107 = QtWidgets.QSpinBox(self.layoutWidget_21)
        self.spinBox_107.setObjectName("spinBox_107")
        self.horizontalLayout_29.addWidget(self.spinBox_107)
        self.spinBox_108 = QtWidgets.QSpinBox(self.layoutWidget_21)
        self.spinBox_108.setObjectName("spinBox_108")
        self.horizontalLayout_29.addWidget(self.spinBox_108)
        self.spinBox_109 = QtWidgets.QSpinBox(self.layoutWidget_21)
        self.spinBox_109.setObjectName("spinBox_109")
        self.horizontalLayout_29.addWidget(self.spinBox_109)
        self.spinBox_110 = QtWidgets.QSpinBox(self.layoutWidget_21)
        self.spinBox_110.setObjectName("spinBox_110")
        self.horizontalLayout_29.addWidget(self.spinBox_110)
        self.layoutWidget_22 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_22.setGeometry(QtCore.QRect(140, 540, 391, 22))
        self.layoutWidget_22.setObjectName("layoutWidget_22")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.layoutWidget_22)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.spinBox_111 = QtWidgets.QSpinBox(self.layoutWidget_22)
        self.spinBox_111.setObjectName("spinBox_111")
        self.horizontalLayout_30.addWidget(self.spinBox_111)
        self.spinBox_112 = QtWidgets.QSpinBox(self.layoutWidget_22)
        self.spinBox_112.setObjectName("spinBox_112")
        self.horizontalLayout_30.addWidget(self.spinBox_112)
        self.spinBox_113 = QtWidgets.QSpinBox(self.layoutWidget_22)
        self.spinBox_113.setObjectName("spinBox_113")
        self.horizontalLayout_30.addWidget(self.spinBox_113)
        self.spinBox_114 = QtWidgets.QSpinBox(self.layoutWidget_22)
        self.spinBox_114.setObjectName("spinBox_114")
        self.horizontalLayout_30.addWidget(self.spinBox_114)
        self.spinBox_115 = QtWidgets.QSpinBox(self.layoutWidget_22)
        self.spinBox_115.setObjectName("spinBox_115")
        self.horizontalLayout_30.addWidget(self.spinBox_115)
        self.layoutWidget_23 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_23.setGeometry(QtCore.QRect(140, 560, 391, 22))
        self.layoutWidget_23.setObjectName("layoutWidget_23")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.layoutWidget_23)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.spinBox_116 = QtWidgets.QSpinBox(self.layoutWidget_23)
        self.spinBox_116.setObjectName("spinBox_116")
        self.horizontalLayout_31.addWidget(self.spinBox_116)
        self.spinBox_117 = QtWidgets.QSpinBox(self.layoutWidget_23)
        self.spinBox_117.setObjectName("spinBox_117")
        self.horizontalLayout_31.addWidget(self.spinBox_117)
        self.spinBox_118 = QtWidgets.QSpinBox(self.layoutWidget_23)
        self.spinBox_118.setObjectName("spinBox_118")
        self.horizontalLayout_31.addWidget(self.spinBox_118)
        self.spinBox_119 = QtWidgets.QSpinBox(self.layoutWidget_23)
        self.spinBox_119.setObjectName("spinBox_119")
        self.horizontalLayout_31.addWidget(self.spinBox_119)
        self.spinBox_120 = QtWidgets.QSpinBox(self.layoutWidget_23)
        self.spinBox_120.setObjectName("spinBox_120")
        self.horizontalLayout_31.addWidget(self.spinBox_120)
        self.layoutWidget_24 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_24.setGeometry(QtCore.QRect(140, 580, 391, 22))
        self.layoutWidget_24.setObjectName("layoutWidget_24")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.layoutWidget_24)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.spinBox_121 = QtWidgets.QSpinBox(self.layoutWidget_24)
        self.spinBox_121.setObjectName("spinBox_121")
        self.horizontalLayout_32.addWidget(self.spinBox_121)
        self.spinBox_122 = QtWidgets.QSpinBox(self.layoutWidget_24)
        self.spinBox_122.setObjectName("spinBox_122")
        self.horizontalLayout_32.addWidget(self.spinBox_122)
        self.spinBox_123 = QtWidgets.QSpinBox(self.layoutWidget_24)
        self.spinBox_123.setObjectName("spinBox_123")
        self.horizontalLayout_32.addWidget(self.spinBox_123)
        self.spinBox_124 = QtWidgets.QSpinBox(self.layoutWidget_24)
        self.spinBox_124.setObjectName("spinBox_124")
        self.horizontalLayout_32.addWidget(self.spinBox_124)
        self.spinBox_125 = QtWidgets.QSpinBox(self.layoutWidget_24)
        self.spinBox_125.setObjectName("spinBox_125")
        self.horizontalLayout_32.addWidget(self.spinBox_125)
        self.comboBox_9 = QtWidgets.QComboBox(Dialog)
        self.comboBox_9.setGeometry(QtCore.QRect(30, 280, 111, 20))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(Dialog)
        self.comboBox_10.setGeometry(QtCore.QRect(30, 260, 111, 20))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_11 = QtWidgets.QComboBox(Dialog)
        self.comboBox_11.setGeometry(QtCore.QRect(30, 300, 111, 20))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_12 = QtWidgets.QComboBox(Dialog)
        self.comboBox_12.setGeometry(QtCore.QRect(30, 320, 111, 20))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_13 = QtWidgets.QComboBox(Dialog)
        self.comboBox_13.setGeometry(QtCore.QRect(30, 340, 111, 20))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_14 = QtWidgets.QComboBox(Dialog)
        self.comboBox_14.setGeometry(QtCore.QRect(30, 360, 111, 20))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_15 = QtWidgets.QComboBox(Dialog)
        self.comboBox_15.setGeometry(QtCore.QRect(30, 380, 111, 20))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_16 = QtWidgets.QComboBox(Dialog)
        self.comboBox_16.setGeometry(QtCore.QRect(30, 400, 111, 20))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_17 = QtWidgets.QComboBox(Dialog)
        self.comboBox_17.setGeometry(QtCore.QRect(30, 420, 111, 20))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_18 = QtWidgets.QComboBox(Dialog)
        self.comboBox_18.setGeometry(QtCore.QRect(30, 440, 111, 20))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_19 = QtWidgets.QComboBox(Dialog)
        self.comboBox_19.setGeometry(QtCore.QRect(30, 460, 111, 20))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_20 = QtWidgets.QComboBox(Dialog)
        self.comboBox_20.setGeometry(QtCore.QRect(30, 480, 111, 20))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_21 = QtWidgets.QComboBox(Dialog)
        self.comboBox_21.setGeometry(QtCore.QRect(30, 500, 111, 20))
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_22 = QtWidgets.QComboBox(Dialog)
        self.comboBox_22.setGeometry(QtCore.QRect(30, 520, 111, 20))
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_23 = QtWidgets.QComboBox(Dialog)
        self.comboBox_23.setGeometry(QtCore.QRect(30, 540, 111, 20))
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_24 = QtWidgets.QComboBox(Dialog)
        self.comboBox_24.setGeometry(QtCore.QRect(30, 560, 111, 20))
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.comboBox_25 = QtWidgets.QComboBox(Dialog)
        self.comboBox_25.setGeometry(QtCore.QRect(30, 580, 111, 20))
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_25.addItem("")
        self.comboBox_26 = QtWidgets.QComboBox(Dialog)
        self.comboBox_26.setGeometry(QtCore.QRect(640, 90, 111, 20))
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_26.addItem("")
        self.layoutWidget_25 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_25.setGeometry(QtCore.QRect(750, 90, 391, 22))
        self.layoutWidget_25.setObjectName("layoutWidget_25")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.layoutWidget_25)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.spinBox_126 = QtWidgets.QSpinBox(self.layoutWidget_25)
        self.spinBox_126.setObjectName("spinBox_126")
        self.horizontalLayout_33.addWidget(self.spinBox_126)
        self.spinBox_127 = QtWidgets.QSpinBox(self.layoutWidget_25)
        self.spinBox_127.setObjectName("spinBox_127")
        self.horizontalLayout_33.addWidget(self.spinBox_127)
        self.spinBox_128 = QtWidgets.QSpinBox(self.layoutWidget_25)
        self.spinBox_128.setObjectName("spinBox_128")
        self.horizontalLayout_33.addWidget(self.spinBox_128)
        self.spinBox_129 = QtWidgets.QSpinBox(self.layoutWidget_25)
        self.spinBox_129.setObjectName("spinBox_129")
        self.horizontalLayout_33.addWidget(self.spinBox_129)
        self.spinBox_130 = QtWidgets.QSpinBox(self.layoutWidget_25)
        self.spinBox_130.setObjectName("spinBox_130")
        self.horizontalLayout_33.addWidget(self.spinBox_130)
        self.comboBox_27 = QtWidgets.QComboBox(Dialog)
        self.comboBox_27.setGeometry(QtCore.QRect(640, 110, 111, 20))
        self.comboBox_27.setObjectName("comboBox_27")
        self.comboBox_27.addItem("")
        self.layoutWidget_26 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_26.setGeometry(QtCore.QRect(750, 110, 391, 22))
        self.layoutWidget_26.setObjectName("layoutWidget_26")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.layoutWidget_26)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.spinBox_131 = QtWidgets.QSpinBox(self.layoutWidget_26)
        self.spinBox_131.setObjectName("spinBox_131")
        self.horizontalLayout_34.addWidget(self.spinBox_131)
        self.spinBox_132 = QtWidgets.QSpinBox(self.layoutWidget_26)
        self.spinBox_132.setObjectName("spinBox_132")
        self.horizontalLayout_34.addWidget(self.spinBox_132)
        self.spinBox_133 = QtWidgets.QSpinBox(self.layoutWidget_26)
        self.spinBox_133.setObjectName("spinBox_133")
        self.horizontalLayout_34.addWidget(self.spinBox_133)
        self.spinBox_134 = QtWidgets.QSpinBox(self.layoutWidget_26)
        self.spinBox_134.setObjectName("spinBox_134")
        self.horizontalLayout_34.addWidget(self.spinBox_134)
        self.spinBox_135 = QtWidgets.QSpinBox(self.layoutWidget_26)
        self.spinBox_135.setObjectName("spinBox_135")
        self.horizontalLayout_34.addWidget(self.spinBox_135)
        self.comboBox_28 = QtWidgets.QComboBox(Dialog)
        self.comboBox_28.setGeometry(QtCore.QRect(640, 130, 111, 20))
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_28.addItem("")
        self.layoutWidget_27 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_27.setGeometry(QtCore.QRect(750, 130, 391, 22))
        self.layoutWidget_27.setObjectName("layoutWidget_27")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.layoutWidget_27)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.spinBox_136 = QtWidgets.QSpinBox(self.layoutWidget_27)
        self.spinBox_136.setObjectName("spinBox_136")
        self.horizontalLayout_35.addWidget(self.spinBox_136)
        self.spinBox_137 = QtWidgets.QSpinBox(self.layoutWidget_27)
        self.spinBox_137.setObjectName("spinBox_137")
        self.horizontalLayout_35.addWidget(self.spinBox_137)
        self.spinBox_138 = QtWidgets.QSpinBox(self.layoutWidget_27)
        self.spinBox_138.setObjectName("spinBox_138")
        self.horizontalLayout_35.addWidget(self.spinBox_138)
        self.spinBox_139 = QtWidgets.QSpinBox(self.layoutWidget_27)
        self.spinBox_139.setObjectName("spinBox_139")
        self.horizontalLayout_35.addWidget(self.spinBox_139)
        self.spinBox_140 = QtWidgets.QSpinBox(self.layoutWidget_27)
        self.spinBox_140.setObjectName("spinBox_140")
        self.horizontalLayout_35.addWidget(self.spinBox_140)
        self.layoutWidget_28 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_28.setGeometry(QtCore.QRect(750, 150, 391, 22))
        self.layoutWidget_28.setObjectName("layoutWidget_28")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.layoutWidget_28)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.spinBox_141 = QtWidgets.QSpinBox(self.layoutWidget_28)
        self.spinBox_141.setObjectName("spinBox_141")
        self.horizontalLayout_36.addWidget(self.spinBox_141)
        self.spinBox_142 = QtWidgets.QSpinBox(self.layoutWidget_28)
        self.spinBox_142.setObjectName("spinBox_142")
        self.horizontalLayout_36.addWidget(self.spinBox_142)
        self.spinBox_143 = QtWidgets.QSpinBox(self.layoutWidget_28)
        self.spinBox_143.setObjectName("spinBox_143")
        self.horizontalLayout_36.addWidget(self.spinBox_143)
        self.spinBox_144 = QtWidgets.QSpinBox(self.layoutWidget_28)
        self.spinBox_144.setObjectName("spinBox_144")
        self.horizontalLayout_36.addWidget(self.spinBox_144)
        self.spinBox_145 = QtWidgets.QSpinBox(self.layoutWidget_28)
        self.spinBox_145.setObjectName("spinBox_145")
        self.horizontalLayout_36.addWidget(self.spinBox_145)
        self.comboBox_29 = QtWidgets.QComboBox(Dialog)
        self.comboBox_29.setGeometry(QtCore.QRect(640, 150, 111, 20))
        self.comboBox_29.setObjectName("comboBox_29")
        self.comboBox_29.addItem("")
        self.layoutWidget_29 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_29.setGeometry(QtCore.QRect(750, 170, 391, 22))
        self.layoutWidget_29.setObjectName("layoutWidget_29")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.layoutWidget_29)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.spinBox_146 = QtWidgets.QSpinBox(self.layoutWidget_29)
        self.spinBox_146.setObjectName("spinBox_146")
        self.horizontalLayout_37.addWidget(self.spinBox_146)
        self.spinBox_147 = QtWidgets.QSpinBox(self.layoutWidget_29)
        self.spinBox_147.setObjectName("spinBox_147")
        self.horizontalLayout_37.addWidget(self.spinBox_147)
        self.spinBox_148 = QtWidgets.QSpinBox(self.layoutWidget_29)
        self.spinBox_148.setObjectName("spinBox_148")
        self.horizontalLayout_37.addWidget(self.spinBox_148)
        self.spinBox_149 = QtWidgets.QSpinBox(self.layoutWidget_29)
        self.spinBox_149.setObjectName("spinBox_149")
        self.horizontalLayout_37.addWidget(self.spinBox_149)
        self.spinBox_150 = QtWidgets.QSpinBox(self.layoutWidget_29)
        self.spinBox_150.setObjectName("spinBox_150")
        self.horizontalLayout_37.addWidget(self.spinBox_150)
        self.comboBox_30 = QtWidgets.QComboBox(Dialog)
        self.comboBox_30.setGeometry(QtCore.QRect(640, 170, 111, 20))
        self.comboBox_30.setObjectName("comboBox_30")
        self.comboBox_30.addItem("")
        self.comboBox_31 = QtWidgets.QComboBox(Dialog)
        self.comboBox_31.setGeometry(QtCore.QRect(640, 190, 111, 20))
        self.comboBox_31.setObjectName("comboBox_31")
        self.comboBox_31.addItem("")
        self.layoutWidget_30 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_30.setGeometry(QtCore.QRect(750, 190, 391, 22))
        self.layoutWidget_30.setObjectName("layoutWidget_30")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.layoutWidget_30)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.spinBox_151 = QtWidgets.QSpinBox(self.layoutWidget_30)
        self.spinBox_151.setObjectName("spinBox_151")
        self.horizontalLayout_38.addWidget(self.spinBox_151)
        self.spinBox_152 = QtWidgets.QSpinBox(self.layoutWidget_30)
        self.spinBox_152.setObjectName("spinBox_152")
        self.horizontalLayout_38.addWidget(self.spinBox_152)
        self.spinBox_153 = QtWidgets.QSpinBox(self.layoutWidget_30)
        self.spinBox_153.setObjectName("spinBox_153")
        self.horizontalLayout_38.addWidget(self.spinBox_153)
        self.spinBox_154 = QtWidgets.QSpinBox(self.layoutWidget_30)
        self.spinBox_154.setObjectName("spinBox_154")
        self.horizontalLayout_38.addWidget(self.spinBox_154)
        self.spinBox_155 = QtWidgets.QSpinBox(self.layoutWidget_30)
        self.spinBox_155.setObjectName("spinBox_155")
        self.horizontalLayout_38.addWidget(self.spinBox_155)
        self.comboBox_32 = QtWidgets.QComboBox(Dialog)
        self.comboBox_32.setGeometry(QtCore.QRect(640, 210, 111, 20))
        self.comboBox_32.setObjectName("comboBox_32")
        self.comboBox_32.addItem("")
        self.layoutWidget_31 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_31.setGeometry(QtCore.QRect(750, 210, 391, 22))
        self.layoutWidget_31.setObjectName("layoutWidget_31")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.layoutWidget_31)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.spinBox_156 = QtWidgets.QSpinBox(self.layoutWidget_31)
        self.spinBox_156.setObjectName("spinBox_156")
        self.horizontalLayout_39.addWidget(self.spinBox_156)
        self.spinBox_157 = QtWidgets.QSpinBox(self.layoutWidget_31)
        self.spinBox_157.setObjectName("spinBox_157")
        self.horizontalLayout_39.addWidget(self.spinBox_157)
        self.spinBox_158 = QtWidgets.QSpinBox(self.layoutWidget_31)
        self.spinBox_158.setObjectName("spinBox_158")
        self.horizontalLayout_39.addWidget(self.spinBox_158)
        self.spinBox_159 = QtWidgets.QSpinBox(self.layoutWidget_31)
        self.spinBox_159.setObjectName("spinBox_159")
        self.horizontalLayout_39.addWidget(self.spinBox_159)
        self.spinBox_160 = QtWidgets.QSpinBox(self.layoutWidget_31)
        self.spinBox_160.setObjectName("spinBox_160")
        self.horizontalLayout_39.addWidget(self.spinBox_160)
        self.comboBox_33 = QtWidgets.QComboBox(Dialog)
        self.comboBox_33.setGeometry(QtCore.QRect(640, 230, 111, 20))
        self.comboBox_33.setObjectName("comboBox_33")
        self.comboBox_33.addItem("")
        self.layoutWidget_32 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_32.setGeometry(QtCore.QRect(750, 230, 391, 22))
        self.layoutWidget_32.setObjectName("layoutWidget_32")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.layoutWidget_32)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.spinBox_161 = QtWidgets.QSpinBox(self.layoutWidget_32)
        self.spinBox_161.setObjectName("spinBox_161")
        self.horizontalLayout_40.addWidget(self.spinBox_161)
        self.spinBox_162 = QtWidgets.QSpinBox(self.layoutWidget_32)
        self.spinBox_162.setObjectName("spinBox_162")
        self.horizontalLayout_40.addWidget(self.spinBox_162)
        self.spinBox_163 = QtWidgets.QSpinBox(self.layoutWidget_32)
        self.spinBox_163.setObjectName("spinBox_163")
        self.horizontalLayout_40.addWidget(self.spinBox_163)
        self.spinBox_164 = QtWidgets.QSpinBox(self.layoutWidget_32)
        self.spinBox_164.setObjectName("spinBox_164")
        self.horizontalLayout_40.addWidget(self.spinBox_164)
        self.spinBox_165 = QtWidgets.QSpinBox(self.layoutWidget_32)
        self.spinBox_165.setObjectName("spinBox_165")
        self.horizontalLayout_40.addWidget(self.spinBox_165)
        self.comboBox_34 = QtWidgets.QComboBox(Dialog)
        self.comboBox_34.setGeometry(QtCore.QRect(640, 250, 111, 20))
        self.comboBox_34.setObjectName("comboBox_34")
        self.comboBox_34.addItem("")
        self.layoutWidget_33 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_33.setGeometry(QtCore.QRect(750, 250, 391, 22))
        self.layoutWidget_33.setObjectName("layoutWidget_33")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.layoutWidget_33)
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.spinBox_166 = QtWidgets.QSpinBox(self.layoutWidget_33)
        self.spinBox_166.setObjectName("spinBox_166")
        self.horizontalLayout_41.addWidget(self.spinBox_166)
        self.spinBox_167 = QtWidgets.QSpinBox(self.layoutWidget_33)
        self.spinBox_167.setObjectName("spinBox_167")
        self.horizontalLayout_41.addWidget(self.spinBox_167)
        self.spinBox_168 = QtWidgets.QSpinBox(self.layoutWidget_33)
        self.spinBox_168.setObjectName("spinBox_168")
        self.horizontalLayout_41.addWidget(self.spinBox_168)
        self.spinBox_169 = QtWidgets.QSpinBox(self.layoutWidget_33)
        self.spinBox_169.setObjectName("spinBox_169")
        self.horizontalLayout_41.addWidget(self.spinBox_169)
        self.spinBox_170 = QtWidgets.QSpinBox(self.layoutWidget_33)
        self.spinBox_170.setObjectName("spinBox_170")
        self.horizontalLayout_41.addWidget(self.spinBox_170)
        self.comboBox_35 = QtWidgets.QComboBox(Dialog)
        self.comboBox_35.setGeometry(QtCore.QRect(640, 270, 111, 20))
        self.comboBox_35.setObjectName("comboBox_35")
        self.comboBox_35.addItem("")
        self.layoutWidget_34 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_34.setGeometry(QtCore.QRect(750, 270, 391, 22))
        self.layoutWidget_34.setObjectName("layoutWidget_34")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.layoutWidget_34)
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.spinBox_171 = QtWidgets.QSpinBox(self.layoutWidget_34)
        self.spinBox_171.setObjectName("spinBox_171")
        self.horizontalLayout_42.addWidget(self.spinBox_171)
        self.spinBox_172 = QtWidgets.QSpinBox(self.layoutWidget_34)
        self.spinBox_172.setObjectName("spinBox_172")
        self.horizontalLayout_42.addWidget(self.spinBox_172)
        self.spinBox_173 = QtWidgets.QSpinBox(self.layoutWidget_34)
        self.spinBox_173.setObjectName("spinBox_173")
        self.horizontalLayout_42.addWidget(self.spinBox_173)
        self.spinBox_174 = QtWidgets.QSpinBox(self.layoutWidget_34)
        self.spinBox_174.setObjectName("spinBox_174")
        self.horizontalLayout_42.addWidget(self.spinBox_174)
        self.spinBox_175 = QtWidgets.QSpinBox(self.layoutWidget_34)
        self.spinBox_175.setObjectName("spinBox_175")
        self.horizontalLayout_42.addWidget(self.spinBox_175)
        self.comboBox_36 = QtWidgets.QComboBox(Dialog)
        self.comboBox_36.setGeometry(QtCore.QRect(640, 290, 111, 20))
        self.comboBox_36.setObjectName("comboBox_36")
        self.comboBox_36.addItem("")
        self.layoutWidget_35 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_35.setGeometry(QtCore.QRect(750, 290, 391, 22))
        self.layoutWidget_35.setObjectName("layoutWidget_35")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.layoutWidget_35)
        self.horizontalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.spinBox_176 = QtWidgets.QSpinBox(self.layoutWidget_35)
        self.spinBox_176.setObjectName("spinBox_176")
        self.horizontalLayout_43.addWidget(self.spinBox_176)
        self.spinBox_177 = QtWidgets.QSpinBox(self.layoutWidget_35)
        self.spinBox_177.setObjectName("spinBox_177")
        self.horizontalLayout_43.addWidget(self.spinBox_177)
        self.spinBox_178 = QtWidgets.QSpinBox(self.layoutWidget_35)
        self.spinBox_178.setObjectName("spinBox_178")
        self.horizontalLayout_43.addWidget(self.spinBox_178)
        self.spinBox_179 = QtWidgets.QSpinBox(self.layoutWidget_35)
        self.spinBox_179.setObjectName("spinBox_179")
        self.horizontalLayout_43.addWidget(self.spinBox_179)
        self.spinBox_180 = QtWidgets.QSpinBox(self.layoutWidget_35)
        self.spinBox_180.setObjectName("spinBox_180")
        self.horizontalLayout_43.addWidget(self.spinBox_180)
        self.comboBox_37 = QtWidgets.QComboBox(Dialog)
        self.comboBox_37.setGeometry(QtCore.QRect(640, 310, 111, 20))
        self.comboBox_37.setObjectName("comboBox_37")
        self.comboBox_37.addItem("")
        self.layoutWidget_36 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_36.setGeometry(QtCore.QRect(750, 310, 391, 22))
        self.layoutWidget_36.setObjectName("layoutWidget_36")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.layoutWidget_36)
        self.horizontalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.spinBox_181 = QtWidgets.QSpinBox(self.layoutWidget_36)
        self.spinBox_181.setObjectName("spinBox_181")
        self.horizontalLayout_44.addWidget(self.spinBox_181)
        self.spinBox_182 = QtWidgets.QSpinBox(self.layoutWidget_36)
        self.spinBox_182.setObjectName("spinBox_182")
        self.horizontalLayout_44.addWidget(self.spinBox_182)
        self.spinBox_183 = QtWidgets.QSpinBox(self.layoutWidget_36)
        self.spinBox_183.setObjectName("spinBox_183")
        self.horizontalLayout_44.addWidget(self.spinBox_183)
        self.spinBox_184 = QtWidgets.QSpinBox(self.layoutWidget_36)
        self.spinBox_184.setObjectName("spinBox_184")
        self.horizontalLayout_44.addWidget(self.spinBox_184)
        self.spinBox_185 = QtWidgets.QSpinBox(self.layoutWidget_36)
        self.spinBox_185.setObjectName("spinBox_185")
        self.horizontalLayout_44.addWidget(self.spinBox_185)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(790, 420, 161, 23))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 80, 461, 16))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(70, 0, 179, 75))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(140, 100, 391, 22))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_3.addWidget(self.spinBox_2)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_3.addWidget(self.spinBox_3)
        self.spinBox_4 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_3.addWidget(self.spinBox_4)
        self.spinBox_5 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_3.addWidget(self.spinBox_5)
#         print(type(self.comboBox.currentText()))
        self.retranslateUi(Dialog)
        self.comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        self.comboBox_4.setCurrentIndex(0)
        self.comboBox_5.setCurrentIndex(0)
        self.comboBox_6.setCurrentIndex(0)
        self.comboBox_7.setCurrentIndex(0)
        self.comboBox_8.setCurrentIndex(0)
        self.comboBox_9.setCurrentIndex(0)
        self.comboBox_10.setCurrentIndex(0)
        self.comboBox_11.setCurrentIndex(0)
        self.comboBox_12.setCurrentIndex(0)
        self.comboBox_13.setCurrentIndex(0)
        self.comboBox_14.setCurrentIndex(0)
        self.comboBox_15.setCurrentIndex(0)
        self.comboBox_16.setCurrentIndex(0)
        self.comboBox_17.setCurrentIndex(0)
        self.comboBox_18.setCurrentIndex(0)
        self.comboBox_19.setCurrentIndex(0)
        self.comboBox_20.setCurrentIndex(0)
        self.comboBox_21.setCurrentIndex(0)
        self.comboBox_22.setCurrentIndex(0)
        self.comboBox_23.setCurrentIndex(0)
        self.comboBox_24.setCurrentIndex(0)
        self.comboBox_25.setCurrentIndex(0)
        self.comboBox_26.setCurrentIndex(0)
        self.comboBox_27.setCurrentIndex(0)
        self.comboBox_28.setCurrentIndex(0)
        self.comboBox_29.setCurrentIndex(0)
        self.comboBox_30.setCurrentIndex(0)
        self.comboBox_31.setCurrentIndex(0)
        self.comboBox_32.setCurrentIndex(0)
        self.comboBox_33.setCurrentIndex(0)
        self.comboBox_34.setCurrentIndex(0)
        self.comboBox_35.setCurrentIndex(0)
        self.comboBox_36.setCurrentIndex(0)
        self.comboBox_37.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.new_data)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBox.setItemText(0, _translate("Dialog", "资产负债率"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "长期资金占不动产/厂房及设备比率"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "流动比率"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "速动比率"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "应收款项周转率"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "应收账款周转天数"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "存货周转率"))
        self.comboBox_8.setItemText(0, _translate("Dialog", "存货周转天数"))
        self.comboBox_9.setItemText(0, _translate("Dialog", "资产收益率"))
        self.comboBox_10.setItemText(0, _translate("Dialog", "固定资产周转率"))
        self.comboBox_11.setItemText(0, _translate("Dialog", "净资产收益率"))
        self.comboBox_12.setItemText(0, _translate("Dialog", "税前纯益占实收资本比率"))
        self.comboBox_13.setItemText(0, _translate("Dialog", "生意完整周期"))
        self.comboBox_14.setItemText(0, _translate("Dialog", "总资产周转率"))
        self.comboBox_15.setItemText(0, _translate("Dialog", "EPS_每股收益"))
        self.comboBox_16.setItemText(0, _translate("Dialog", "营收增长率"))
        self.comboBox_17.setItemText(0, _translate("Dialog", "净利润增长率"))
        self.comboBox_18.setItemText(0, _translate("Dialog", "净资产增长率"))
        self.comboBox_19.setItemText(0, _translate("Dialog", "现金流量比率"))
        self.comboBox_20.setItemText(0, _translate("Dialog", "现金流量允当比率"))
        self.comboBox_21.setItemText(0, _translate("Dialog", "现金再投资比率"))
        self.comboBox_22.setItemText(0, _translate("Dialog", "毛利率"))
        self.comboBox_23.setItemText(0, _translate("Dialog", "营业利润率"))
        self.comboBox_24.setItemText(0, _translate("Dialog", "净利润率"))
        self.comboBox_25.setItemText(0, _translate("Dialog", "营业费用率"))
        self.comboBox_26.setItemText(0, _translate("Dialog", "经营安全边际率 "))
        self.comboBox_27.setItemText(0, _translate("Dialog", "现金与约当现金比率"))
        self.comboBox_28.setItemText(0, _translate("Dialog", "应收款项(占总资产%)"))
        self.comboBox_29.setItemText(0, _translate("Dialog", "存货(占总资产%)"))
        self.comboBox_30.setItemText(0, _translate("Dialog", "流动资产(占总资产%)"))
        self.comboBox_31.setItemText(0, _translate("Dialog", "非流动资产"))
        self.comboBox_32.setItemText(0, _translate("Dialog", "总资产(占总资产%)"))
        self.comboBox_33.setItemText(0, _translate("Dialog", "应付款项(占总资产%)"))
        self.comboBox_34.setItemText(0, _translate("Dialog", "流动负债(占总资产%)"))
        self.comboBox_35.setItemText(0, _translate("Dialog", "非流动负债(占总资产%)"))
        self.comboBox_36.setItemText(0, _translate("Dialog", "股东权益(占总资产%)"))
        self.comboBox_37.setItemText(0, _translate("Dialog", "负债和所有者权益(占总资产%)"))
        self.pushButton.setText(_translate("Dialog", "confirm to updata"))
        self.label_2.setText(_translate("Dialog", "Id:"))
        self.label_3.setText(_translate("Dialog", "2017"))
        self.label_4.setText(_translate("Dialog", "2016"))
        self.label_5.setText(_translate("Dialog", "2015"))
        self.label_6.setText(_translate("Dialog", "2014"))
        self.label_7.setText(_translate("Dialog", "2013"))
        self.label.setText(_translate("Dialog", "name:"))
    def new_data(self):
        firm_name=self.lineEdit.text()#新建公司名
        conn = sqlite3.connect(r'db\dataBase.db')
        conn.isolation_level = None
        conn.commit()
        cur = conn.cursor()
        try:#判断打开文件是否出错
            #创建该公司的表
            sql_1="create table if not exists %s"%(firm_name)+"(id varchar(128), \
            Yeas_2017 varchar(128),Yeas_2016 varchar(128),Yeas_2015 varchar(128),\
            Yeas_2014 varchar(128),Yeas_2013 varchar(128))"
            sql_2="INSERT INTO %s"%(firm_name)+" (id,Yeas_2017,Yeas_2016,Yeas_2015,\
            Yeas_2014,Yeas_2013) VALUES (:d1,:d2,:d3,:d4,:d5,:d6)"
            cur.execute(sql_1)
            cur.execute(sql_2,{'d1':self.comboBox.currentText(),'d2':str(self.spinBox.value()),\
                               'd3':str(self.spinBox_2.value()),'d4':str(self.spinBox_3.value()),\
                               'd5':str(self.spinBox_4.value()),'d6':str(self.spinBox_5.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_2.currentText(),'d2':str(self.spinBox_6.value()),\
                               'd3':str(self.spinBox_7.value()),'d4':str(self.spinBox_8.value()),\
                               'd5':str(self.spinBox_9.value()),'d6':str(self.spinBox_10.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_3.currentText(),'d2':str(self.spinBox_11.value()),\
                               'd3':str(self.spinBox_12.value()),'d4':str(self.spinBox_13.value()),\
                               'd5':str(self.spinBox_14.value()),'d6':str(self.spinBox_15.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_4.currentText(),'d2':str(self.spinBox_16.value()),\
                               'd3':str(self.spinBox_17.value()),'d4':str(self.spinBox_18.value()),\
                               'd5':str(self.spinBox_19.value()),'d6':str(self.spinBox_20.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_5.currentText(),'d2':str(self.spinBox_21.value()),\
                               'd3':str(self.spinBox_22.value()),'d4':str(self.spinBox_23.value()),\
                               'd5':str(self.spinBox_24.value()),'d6':str(self.spinBox_25.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_6.currentText(),'d2':str(self.spinBox_26.value()),\
                               'd3':str(self.spinBox_27.value()),'d4':str(self.spinBox_28.value()),\
                               'd5':str(self.spinBox_29.value()),'d6':str(self.spinBox_30.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_7.currentText(),'d2':str(self.spinBox_31.value()),\
                               'd3':str(self.spinBox_32.value()),'d4':str(self.spinBox_33.value()),\
                               'd5':str(self.spinBox_34.value()),'d6':str(self.spinBox_35.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_8.currentText(),'d2':str(self.spinBox_36.value()),\
                               'd3':str(self.spinBox_37.value()),'d4':str(self.spinBox_38.value()),\
                               'd5':str(self.spinBox_39.value()),'d6':str(self.spinBox_40.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_9.currentText(),'d2':str(self.spinBox_41.value()),\
                               'd3':str(self.spinBox_41.value()),'d4':str(self.spinBox_43.value()),\
                               'd5':str(self.spinBox_44.value()),'d6':str(self.spinBox_45.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_10.currentText(),'d2':str(self.spinBox_46.value()),\
                               'd3':str(self.spinBox_47.value()),'d4':str(self.spinBox_48.value()),\
                               'd5':str(self.spinBox_49.value()),'d6':str(self.spinBox_50.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_11.currentText(),'d2':str(self.spinBox_51.value()),\
                               'd3':str(self.spinBox_52.value()),'d4':str(self.spinBox_53.value()),\
                               'd5':str(self.spinBox_54.value()),'d6':str(self.spinBox_55.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_12.currentText(),'d2':str(self.spinBox_56.value()),\
                               'd3':str(self.spinBox_57.value()),'d4':str(self.spinBox_58.value()),\
                               'd5':str(self.spinBox_59.value()),'d6':str(self.spinBox_60.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_13.currentText(),'d2':str(self.spinBox_61.value()),\
                               'd3':str(self.spinBox_62.value()),'d4':str(self.spinBox_63.value()),\
                               'd5':str(self.spinBox_64.value()),'d6':str(self.spinBox_65.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_14.currentText(),'d2':str(self.spinBox_66.value()),\
                               'd3':str(self.spinBox_67.value()),'d4':str(self.spinBox_68.value()),\
                               'd5':str(self.spinBox_69.value()),'d6':str(self.spinBox_70.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_15.currentText(),'d2':str(self.spinBox_71.value()),\
                               'd3':str(self.spinBox_72.value()),'d4':str(self.spinBox_73.value()),\
                               'd5':str(self.spinBox_74.value()),'d6':str(self.spinBox_75.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_16.currentText(),'d2':str(self.spinBox_76.value()),\
                               'd3':str(self.spinBox_77.value()),'d4':str(self.spinBox_78.value()),\
                               'd5':str(self.spinBox_79.value()),'d6':str(self.spinBox_80.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_17.currentText(),'d2':str(self.spinBox_81.value()),\
                               'd3':str(self.spinBox_82.value()),'d4':str(self.spinBox_83.value()),\
                               'd5':str(self.spinBox_84.value()),'d6':str(self.spinBox_85.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_18.currentText(),'d2':str(self.spinBox_86.value()),\
                               'd3':str(self.spinBox_87.value()),'d4':str(self.spinBox_88.value()),\
                               'd5':str(self.spinBox_89.value()),'d6':str(self.spinBox_90.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_19.currentText(),'d2':str(self.spinBox_91.value()),\
                               'd3':str(self.spinBox_92.value()),'d4':str(self.spinBox_93.value()),\
                               'd5':str(self.spinBox_94.value()),'d6':str(self.spinBox_95.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_20.currentText(),'d2':str(self.spinBox_96.value()),\
                               'd3':str(self.spinBox_97.value()),'d4':str(self.spinBox_98.value()),\
                               'd5':str(self.spinBox_99.value()),'d6':str(self.spinBox_100.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_21.currentText(),'d2':str(self.spinBox_101.value()),\
                               'd3':str(self.spinBox_102.value()),'d4':str(self.spinBox_103.value()),\
                               'd5':str(self.spinBox_104.value()),'d6':str(self.spinBox_105.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_22.currentText(),'d2':str(self.spinBox_106.value()),\
                               'd3':str(self.spinBox_107.value()),'d4':str(self.spinBox_108.value()),\
                               'd5':str(self.spinBox_109.value()),'d6':str(self.spinBox_110.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_23.currentText(),'d2':str(self.spinBox_111.value()),\
                               'd3':str(self.spinBox_112.value()),'d4':str(self.spinBox_113.value()),\
                               'd5':str(self.spinBox_114.value()),'d6':str(self.spinBox_115.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_24.currentText(),'d2':str(self.spinBox_116.value()),\
                               'd3':str(self.spinBox_117.value()),'d4':str(self.spinBox_118.value()),\
                               'd5':str(self.spinBox_119.value()),'d6':str(self.spinBox_120.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_25.currentText(),'d2':str(self.spinBox_121.value()),\
                               'd3':str(self.spinBox_122.value()),'d4':str(self.spinBox_123.value()),\
                               'd5':str(self.spinBox_124.value()),'d6':str(self.spinBox_125.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_26.currentText(),'d2':str(self.spinBox_126.value()),\
                               'd3':str(self.spinBox_127.value()),'d4':str(self.spinBox_128.value()),\
                               'd5':str(self.spinBox_129.value()),'d6':str(self.spinBox_130.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_27.currentText(),'d2':str(self.spinBox_131.value()),\
                               'd3':str(self.spinBox_132.value()),'d4':str(self.spinBox_133.value()),\
                               'd5':str(self.spinBox_134.value()),'d6':str(self.spinBox_135.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_28.currentText(),'d2':str(self.spinBox_136.value()),\
                               'd3':str(self.spinBox_137.value()),'d4':str(self.spinBox_138.value()),\
                               'd5':str(self.spinBox_139.value()),'d6':str(self.spinBox_140.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_29.currentText(),'d2':str(self.spinBox_141.value()),\
                               'd3':str(self.spinBox_142.value()),'d4':str(self.spinBox_143.value()),\
                               'd5':str(self.spinBox_144.value()),'d6':str(self.spinBox_145.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_30.currentText(),'d2':str(self.spinBox_146.value()),\
                               'd3':str(self.spinBox_147.value()),'d4':str(self.spinBox_148.value()),\
                               'd5':str(self.spinBox_149.value()),'d6':str(self.spinBox_150.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_31.currentText(),'d2':str(self.spinBox_151.value()),\
                               'd3':str(self.spinBox_152.value()),'d4':str(self.spinBox_153.value()),\
                               'd5':str(self.spinBox_154.value()),'d6':str(self.spinBox_155.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_32.currentText(),'d2':str(self.spinBox_156.value()),\
                               'd3':str(self.spinBox_157.value()),'d4':str(self.spinBox_158.value()),\
                               'd5':str(self.spinBox_159.value()),'d6':str(self.spinBox_160.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_33.currentText(),'d2':str(self.spinBox_161.value()),\
                               'd3':str(self.spinBox_162.value()),'d4':str(self.spinBox_163.value()),\
                               'd5':str(self.spinBox_164.value()),'d6':str(self.spinBox_165.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_34.currentText(),'d2':str(self.spinBox_166.value()),\
                               'd3':str(self.spinBox_167.value()),'d4':str(self.spinBox_168.value()),\
                               'd5':str(self.spinBox_169.value()),'d6':str(self.spinBox_170.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_35.currentText(),'d2':str(self.spinBox_171.value()),\
                               'd3':str(self.spinBox_172.value()),'d4':str(self.spinBox_173.value()),\
                               'd5':str(self.spinBox_174.value()),'d6':str(self.spinBox_175.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_36.currentText(),'d2':str(self.spinBox_176.value()),\
                               'd3':str(self.spinBox_177.value()),'d4':str(self.spinBox_178.value()),\
                               'd5':str(self.spinBox_179.value()),'d6':str(self.spinBox_180.value())})
            
            cur.execute(sql_2,{'d1':self.comboBox_37.currentText(),'d2':str(self.spinBox_181.value()),\
                               'd3':str(self.spinBox_182.value()),'d4':str(self.spinBox_183.value()),\
                               'd5':str(self.spinBox_184.value()),'d6':str(self.spinBox_185.value())})
            conn.commit()
            QtWidgets.QMessageBox.information(self,"info","企业"+self.lineEdit.text()+"成功添加到数据库")
#             print("A")
        except Exception as err:
#             print("laji")
            QtWidgets.QMessageBox.information(self,"info","遇到一些错误，请重试")
            print(err)
        
class query_interface(QDialog):
#     print("hah")
    def __init__(self):
      super(query_interface, self).__init__()
      self.ui=Ui_Dialog()
      self.ui.setupUi(self)
          
 
if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    myapp=query_interface()
    #myapp.setupUi()
    myapp.exec_()
    sys.exit(app.exec_())
